# Generated by Django 4.1.7 on 2023-04-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopapointment',
            name='services',
            field=models.CharField(max_length=100),
        ),
    ]
