# Generated by Django 4.1.7 on 2023-04-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_shopapointment_name1_shopapointment_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='services',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
