# Generated by Django 4.1.7 on 2023-04-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_employee_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='services',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
